### ISSUE TITLE
zun_compute_k8s gets unhealthy with no errors

### ISSUE THREAD

**Issue by samiemostafavi** [ChameleonCloud/chi-in-a-box#246]
Hi,

We have a really annoying problem with zun_compute_k8s. A couple of hours after a clean deploy, `zun_compute_k8s` service becomes unhealthy. Non of the functions work at this stage thanks to `check_container_host `s in `zun/compute/rpcapi.py`. I cannot create a container or see the logs. The only way out of this is that I restart the zun_compute_k8s by running `docker restart zun_compute_k8s`. Then I will have a couple of hours more.

I read the logs of all zun related services but non of them show any error or even warning.
```
docker exec -it zun_compute_k8s cat /var/log/kolla/zun/zun-compute.log
docker exec -it zun_api cat /var/log/kolla/zun/zun-api.log
```

Is there anyway out of this?

Best,
Samie

**Comment by samiemostafavi** [comment]
I found the following error, could this be the reason? If yes, is there any workarounds for it?

```
Traceback (most recent call last):
  File "/var/lib/kolla/venv/lib/python3.8/site-packages/eventlet/hubs/hub.py", line 476, in fire_timers
    timer()
  File "/var/lib/kolla/venv/lib/python3.8/site-packages/eventlet/hubs/timer.py", line 59, in __call__
    cb(*args, **kw)
  File "/var/lib/kolla/venv/lib/python3.8/site-packages/eventlet/semaphore.py", line 152, in _do_acquire
    waiter.switch()
greenlet.error: cannot switch to a different thread
```

**Comment by samiemostafavi** [comment]
Now I am sure the problem is related to eventlet and was brought up here: [https://github.com/eventlet/eventlet/issues/432](https://github.com/eventlet/eventlet/issues/432).

Similar problems in
- Cinder: [github.com/openstack-k8s-operators/cinder-operator/pull/12](https://github.com/openstack-k8s-operators/cinder-operator/pull/12)
- Oslo messaging: [bugs.launchpad.net/oslo.messaging/+bug/1934937](https://bugs.launchpad.net/oslo.messaging/+bug/1934937)
- Oslo logging: [review.opendev.org/c/openstack/oslo.log/+/852443](https://review.opendev.org/c/openstack/oslo.log/+/852443)
[bugs.launchpad.net/oslo.log/+bug/1983863](https://bugs.launchpad.net/oslo.log/+bug/1983863)

I tried downgrading eventlet on zun_compute_k8s to 0.29.0 but did not help. Also upgrading oslo.log and oslo.messaging did not help either.

It seems eventlet is used in such a way that native threads and green threads are mixed there. This issue is very critical to us and prevents any further development. If you could suggest some workarounds I would really appreciate.

**Comment by samiemostafavi** [comment]
Hi,

I think I have narrowed down the problem. The error shows up when there is Oslo logging (for example `LOG.info()`) inside an eventlet thread. We had some `LOG.info()` lines in container creation function at `zun/container/k8s/driver.py` and after I commented them we don't see the error anymore.

**Comment by msherman64** [comment]
@samiemostafavi Thanks for this, I'm investigating it now, and should have a fix merged soon.
